# Generated by Django 5.0.2 on 2024-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_profile_author_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displayname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
