# Generated by Django 5.0.2 on 2024-05-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='objects_id',
            new_name='object_id',
        ),
    ]
