# Generated by Django 5.0.2 on 2024-05-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_rename_objects_id_tag_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
    ]
